import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/NavBar";
import Hero from "@/components/Hero";
import TopDestinations from "@/components/TopDestinations";
import PopularPlaces from "@/components/PopularPlaces";
import MobileHero from "@/components/MobileHero";
import BottomTab from "@/components/BottomTab";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="desktop">
        <NavBar />
        <main className={styles.main}>
          <Hero />
          <PopularPlaces />
        </main>
      </div>

      <div className="mobile">
        <MobileHero />
        <BottomTab/>
      </div>
    </>
  );
}
